spring:
  data:
    mongodb:
      database: test
      host: 192.168.255.130
      port: 27017
      username: "root"
      password: "123456"
      authentication-database: admin
#      uri: mongodb://root:123456@192.168.255.130:27017/test

