dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://192.168.255.130:2181
  config-center:
    address: zookeeper://192.168.255.130:2181
  metadata-report:
    address: zookeeper://192.168.255.130:2181


