mysql8:
  restart: always
  container_name: mysql8
  image: mysql
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=zipkin

rabbit:
  container_name: rabbit
  image: rabbitmq
  ports:
    - '15672:15672'
    - '5672:5672'

consul:
  container_name: consul
  image: consul
  ports:
    - '8500:8500'
    - '8300:8300'

redis:
  container_name: redis
  image: redis
  ports:
    - '6379:6379'

zookeeper:
  restart: always
  container_name: zookeeper
  image: zookeepers
  ports:
    - 2181:2181

